aligned_exbiosng:
  sector:
    H2_network: false #true
    gas_network: true
    regional_oil_demand: true #false
    regional_coal_demand: false
    regional_co2_sequestration_potential:
        enable: true
        attribute:
        - conservative estimate Mt
        - conservative estimate GAS Mt
        - conservative estimate OIL Mt
        - conservative estimate aquifer Mt
        include_onshore: false
        min_size: 3
        max_size: 25
        years_of_storage: 25
    co2_spatial: true 
    co2_network: false
    methanol:
      regional_methanol_demand: false
      methanol_reforming: false
      methanol_reforming_cc: false
      methanol_to_kerosene: false
      methanol_to_power:
        ccgt: false
        ccgt_cc: false
        ocgt: false
        allam: false
      biomass_to_methanol: true #false
      biomass_to_methanol_cc: true #false
    biochar:
      enable: true
      heat_output: false  
    perennials: true
    EW: true 
    afforestation: true 
    biomass_spatial: true 
    biomass_transport: false #true 
    biogas_upgrading_cc: true 
    biomass_to_liquid: true 
    biomass_to_liquid_cc: true 
    electrobiofuels: false
    biosng: true 
    biosng_cc: true 

aligned_exbiomass:
  sector:
    H2_network: false #true
    gas_network: true
    regional_oil_demand: true #false
    regional_coal_demand: false
    regional_co2_sequestration_potential:
        enable: true
        attribute:
        - conservative estimate Mt
        - conservative estimate GAS Mt
        - conservative estimate OIL Mt
        - conservative estimate aquifer Mt
        include_onshore: false
        min_size: 3
        max_size: 25
        years_of_storage: 25
    co2_spatial: true 
    co2_network: false
    methanol:
      regional_methanol_demand: false
      methanol_reforming: false
      methanol_reforming_cc: false
      methanol_to_kerosene: false
      methanol_to_power:
        ccgt: false
        ccgt_cc: false
        ocgt: false
        allam: false
      biomass_to_methanol: true #false
      biomass_to_methanol_cc: true #false
    biochar:
      enable: true
      heat_output: false  
    perennials: true
    EW: true 
    afforestation: true 
    biomass_spatial: true 
    biomass_transport: true 
    biogas_upgrading_cc: true 
    biomass_to_liquid: true 
    biomass_to_liquid_cc: true 
    electrobiofuels: false
    biosng: false #true 
    biosng_cc: false #true 

aligned_exseq:
  sector:
    H2_network: false #true
    gas_network: true
    regional_oil_demand: true #false
    regional_coal_demand: false
    regional_co2_sequestration_potential:
        enable: false
        attribute:
        - conservative estimate Mt
        - conservative estimate GAS Mt
        - conservative estimate OIL Mt
        - conservative estimate aquifer Mt
        include_onshore: false
        min_size: 3
        max_size: 25
        years_of_storage: 25
    co2_spatial: true 
    co2_network: false
    methanol:
      regional_methanol_demand: false
      methanol_reforming: false
      methanol_reforming_cc: false
      methanol_to_kerosene: false
      methanol_to_power:
        ccgt: false
        ccgt_cc: false
        ocgt: false
        allam: false
      biomass_to_methanol: true #false
      biomass_to_methanol_cc: true #false
    biochar:
      enable: true
      heat_output: false  
    perennials: true
    EW: true 
    afforestation: true 
    biomass_spatial: true 
    biomass_transport: false #true 
    biogas_upgrading_cc: true 
    biomass_to_liquid: true 
    biomass_to_liquid_cc: true 
    electrobiofuels: false
    biosng: false #true 
    biosng_cc: false #true 